/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KHADIJA
 */
public class AddNewProductsIntoSale extends javax.swing.JFrame {

    /**
     * Creates new form AddNewProductsIntoSale
     */
    public AddNewProductsIntoSale() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        closePannel = new javax.swing.JPanel();
        CloseLabel = new javax.swing.JLabel();
        MinPannel = new javax.swing.JPanel();
        MinLabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        SalePer = new javax.swing.JComboBox<>();
        time = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        desc = new javax.swing.JTextArea();
        type = new javax.swing.JComboBox<>();
        quan = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(190, 21, 88));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(190, 21, 88));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closePannel.setBackground(new java.awt.Color(190, 21, 88));

        CloseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CloseLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/icons8_multiply_40px.png"))); // NOI18N
        CloseLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CloseLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CloseLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout closePannelLayout = new javax.swing.GroupLayout(closePannel);
        closePannel.setLayout(closePannelLayout);
        closePannelLayout.setHorizontalGroup(
            closePannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CloseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        closePannelLayout.setVerticalGroup(
            closePannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CloseLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel3.add(closePannel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 70, 60));

        MinPannel.setBackground(new java.awt.Color(190, 21, 88));

        MinLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MinLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/icons8_minimize_window_40px_1.png"))); // NOI18N
        MinLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MinLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MinLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout MinPannelLayout = new javax.swing.GroupLayout(MinPannel);
        MinPannel.setLayout(MinPannelLayout);
        MinPannelLayout.setHorizontalGroup(
            MinPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MinLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        MinPannelLayout.setVerticalGroup(
            MinPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MinLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel3.add(MinPannel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 70, 60));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 220, 60));

        jPanel6.setBackground(new java.awt.Color(190, 21, 88));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("One-Click Pick");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 88, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 270, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(190, 21, 88));
        jLabel2.setText("      Sales Products");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 250, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(190, 21, 88));
        jLabel5.setText("Product ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(190, 21, 88));
        jLabel4.setText("Price");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(190, 21, 88));
        jLabel3.setText("Sale Percentage");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(190, 21, 88));
        jLabel6.setText("Sales Time Duration");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, -1, -1));

        name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(190, 21, 88)));
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 340, 30));

        price.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(190, 21, 88)));
        jPanel1.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 340, 30));

        SalePer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10%", "20%", "30%", "40%", "50%", "60%", "70%", "80%", "90%", "100%" }));
        SalePer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalePerActionPerformed(evt);
            }
        });
        jPanel1.add(SalePer, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 340, 30));

        time.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(190, 21, 88)));
        jPanel1.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, 340, 30));

        AddButton.setBackground(new java.awt.Color(190, 21, 88));
        AddButton.setForeground(new java.awt.Color(255, 255, 255));
        AddButton.setText("Add Product");
        AddButton.setBorder(null);
        AddButton.setBorderPainted(false);
        AddButton.setDefaultCapable(false);
        AddButton.setFocusPainted(false);
        AddButton.setFocusable(false);
        AddButton.setRequestFocusEnabled(false);
        AddButton.setRolloverEnabled(false);
        AddButton.setVerifyInputWhenFocusTarget(false);
        AddButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddButtonMouseExited(evt);
            }
        });
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 550, 140, 40));

        UpdateButton.setBackground(new java.awt.Color(190, 21, 88));
        UpdateButton.setForeground(new java.awt.Color(255, 255, 255));
        UpdateButton.setText("Update Product Sale");
        UpdateButton.setBorder(null);
        UpdateButton.setBorderPainted(false);
        UpdateButton.setDefaultCapable(false);
        UpdateButton.setFocusPainted(false);
        UpdateButton.setFocusable(false);
        UpdateButton.setRequestFocusEnabled(false);
        UpdateButton.setRolloverEnabled(false);
        UpdateButton.setVerifyInputWhenFocusTarget(false);
        UpdateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UpdateButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UpdateButtonMouseExited(evt);
            }
        });
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });
        jPanel1.add(UpdateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 550, 140, 40));

        DeleteButton.setBackground(new java.awt.Color(190, 21, 88));
        DeleteButton.setForeground(new java.awt.Color(255, 255, 255));
        DeleteButton.setText("Remove Product");
        DeleteButton.setBorder(null);
        DeleteButton.setBorderPainted(false);
        DeleteButton.setDefaultCapable(false);
        DeleteButton.setFocusPainted(false);
        DeleteButton.setFocusable(false);
        DeleteButton.setRequestFocusEnabled(false);
        DeleteButton.setRolloverEnabled(false);
        DeleteButton.setVerifyInputWhenFocusTarget(false);
        DeleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DeleteButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DeleteButtonMouseExited(evt);
            }
        });
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });
        jPanel1.add(DeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 550, 150, 40));

        jTable1.setForeground(new java.awt.Color(190, 21, 88));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Name", "Quantity", "Price", "Type", "Sale Percentage", "Sale Time"
            }
        ));
        jTable1.setSelectionBackground(new java.awt.Color(190, 21, 88));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, 900, 90));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(190, 21, 88));
        jLabel7.setText("Name");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(190, 21, 88));
        jLabel8.setText("Quantity");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(190, 21, 88));
        jLabel9.setText("Type");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));

        id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(190, 21, 88)));
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 340, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(190, 21, 88));
        jLabel10.setText("Description");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, -1, 30));

        desc.setColumns(20);
        desc.setRows(5);
        jScrollPane2.setViewportView(desc);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 470, 340, 50));

        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grocery", "Dresses", "Books", "Stationary", "Pharmacy", "Home Appliances", "" }));
        type.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(190, 21, 88)));
        jPanel1.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 340, 30));

        quan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        quan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(190, 21, 88)));
        quan.setFocusable(false);
        quan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanActionPerformed(evt);
            }
        });
        jPanel1.add(quan, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 340, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/2.jpg"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 920, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 public void changeColor(JPanel hover, Color rand) {
        hover.setBackground(rand);
    }
    private void CloseLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_CloseLabelMouseClicked

    private void CloseLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMouseEntered
        // TODO add your handling code here:
        changeColor(closePannel, new Color(222, 142, 174));
    }//GEN-LAST:event_CloseLabelMouseEntered

    private void CloseLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMouseExited
        // TODO add your handling code here:
        changeColor(closePannel, new Color(190, 21, 88));
    }//GEN-LAST:event_CloseLabelMouseExited

    private void MinLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinLabelMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(MainScreen.ICONIFIED);
    }//GEN-LAST:event_MinLabelMouseClicked

    private void MinLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinLabelMouseEntered
        // TODO add your handling code here:
        changeColor(MinPannel, new Color(222, 142, 174));
    }//GEN-LAST:event_MinLabelMouseEntered

    private void MinLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinLabelMouseExited
        // TODO add your handling code here:
        changeColor(MinPannel, new Color(190, 21, 88));
    }//GEN-LAST:event_MinLabelMouseExited

    private void SalePerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalePerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalePerActionPerformed

    private void AddButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButtonMouseEntered
        // TODO add your handling code here:
        AddButton.setBackground(new Color(222, 142, 174));
    }//GEN-LAST:event_AddButtonMouseEntered

    private void AddButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButtonMouseExited
        // TODO add your handling code here:
        AddButton.setBackground(new Color(190, 21, 88));
    }//GEN-LAST:event_AddButtonMouseExited

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
        Sales s = new Sales();
        Validator check = new Validator();
        s.setProductID(id.getText());
        s.setProductName(name.getText());
        s.setProductType(type.getSelectedItem().toString());
        int quantity = Integer.parseInt(quan.getSelectedItem().toString());
        s.setProductQuantity(quantity);
        int p = Integer.parseInt(price.getText());
        s.setProductPrice(p);
        s.setSalesPercentage(SalePer.getSelectedItem().toString());
        s.setSalesTimeDuration(time.getText());
        s.setDes(desc.getText());
        boolean checkProductID = check.ProductID(s.getProductID());
        boolean checkProductName = check.ProductName(s.getProductName());
        boolean checkProductPrice = check.ProductPrice(s.getProductPrice());
        if (name.getText().equals("") || id.getText().equals("") || price.getText().equals("") || quan.getSelectedItem().toString().equals("") || type.getSelectedItem().toString().equals("") || time.getText().equals("")
                || desc.getText().equals("") || SalePer.getSelectedItem().toString().equals("")) {

            JOptionPane.showMessageDialog(null, "You have not entered all required Data");
        } else {
            if (checkProductID == true && checkProductName == true && checkProductPrice == true) {
                String data[] = {id.getText(), name.getText(), quan.getSelectedItem().toString(), price.getText(), type.getSelectedItem().toString(),
                    SalePer.getSelectedItem().toString(), time.getText()};
                DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
                tableModel.addRow(data);
                M.addProductsSales(s);
                JOptionPane.showMessageDialog(null, "Your Data saved Successfully");
                for (int i = 0; i < M.getSalesList().size(); i++) {
                    Sales sales = (Sales) (M.getSalesList().get(i));
                    JOptionPane.showMessageDialog(null, sales + sales.getSalesPercentage()
                            + sales.getSalesTimeDuration()
                    );
                }
                id.setText("");
                name.setText("");
                price.setText("");
                desc.setText("");
                time.setText("");
            } else {
                System.out.println("Products Invalid");
            }
        }

    }//GEN-LAST:event_AddButtonActionPerformed

    private void UpdateButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateButtonMouseEntered
        // TODO add your handling code here:
        UpdateButton.setBackground(new Color(222, 142, 174));
    }//GEN-LAST:event_UpdateButtonMouseEntered

    private void UpdateButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateButtonMouseExited
        // TODO add your handling code here:
        UpdateButton.setBackground(new Color(190, 21, 88));
    }//GEN-LAST:event_UpdateButtonMouseExited

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
        if (jTable1.getSelectedRowCount() == 1) {
            Sales sales = new Sales();
            int p = 0;
            try {
                p = Integer.parseInt(price.getText());
            } catch (Exception e) {
            }
            Validator check = new Validator();
            boolean checkProductPrice = check.ProductPrice(p);
            boolean checkProductID = check.ProductID(id.getText());
            boolean checkProductName = check.ProductName(name.getText());
            if (checkProductPrice == true && checkProductName == true && checkProductID == true) {
                sales.setProductPrice(p);
                sales.setSalesPercentage(SalePer.getSelectedItem().toString());
                sales.setSalesTimeDuration(time.getText());
                sales.setProductID(id.getText());
                sales.setProductName(name.getText());
                int quantity = Integer.parseInt(quan.getSelectedItem().toString());
                sales.setProductQuantity(quantity);
                sales.setProductType(type.getSelectedItem().toString());
                for (int i = 0; i < M.SalesList.size(); i++) {
                    Sales s = (Sales) (M.getSalesList().get(i));
                    if (s.getProductID().equals("")) {
                        String ID = id.getText();
                        String proName = name.getText();
                        String proType = type.getSelectedItem().toString();
                        String q = quan.getSelectedItem().toString();
                        String Productprice = price.getText();
                        String perc = SalePer.getSelectedItem().toString();
                        String times = time.getText();
                        tableModel.setValueAt(ID, jTable1.getSelectedRow(), 0);
                        tableModel.setValueAt(proName, jTable1.getSelectedRow(), 1);
                        tableModel.setValueAt(proType, jTable1.getSelectedRow(), 2);
                        tableModel.setValueAt(q, jTable1.getSelectedRow(), 3);
                        tableModel.setValueAt(Productprice, jTable1.getSelectedRow(), 4);
                        tableModel.setValueAt(perc, jTable1.getSelectedRow(), 5);
                        tableModel.setValueAt(times, jTable1.getSelectedRow(), 6);
                        M.SalesList.set(i, sales);
                    }
                }

                JOptionPane.showMessageDialog(null, "Data has been updated successfully");
                for (int i = 0; i < M.SalesList.size(); i++) {
                    Sales s = (Sales) (M.getSalesList().get(i));
                    JOptionPane.showMessageDialog(null, s + s.getSalesPercentage()
                            + s.getNewPrice() + s.getSalesTimeDuration()
                    );
                }
                id.setText("");
                name.setText("");
                time.setText("");
                desc.setText("");
                price.setText("");

            }
        } else {
            if (jTable1.getSelectedRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "You have not selected any Row or may be selected Multiple Rows");
            } else {
                JOptionPane.showMessageDialog(null, "Update Failed");

            }
        }


    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void DeleteButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteButtonMouseEntered
        // TODO add your handling code here:
        DeleteButton.setBackground(new Color(222, 142, 174));
    }//GEN-LAST:event_DeleteButtonMouseEntered

    private void DeleteButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteButtonMouseExited
        // TODO add your handling code here:
        DeleteButton.setBackground(new Color(190, 21, 88));
    }//GEN-LAST:event_DeleteButtonMouseExited

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
        String ID = tableModel.getValueAt(jTable1.getSelectedRow(), 0).toString();
        String proName = tableModel.getValueAt(jTable1.getSelectedRow(), 1).toString();
        String proType = tableModel.getValueAt(jTable1.getSelectedRow(), 2).toString();
        String quantity = tableModel.getValueAt(jTable1.getSelectedRow(), 3).toString();
        String proPrice = tableModel.getValueAt(jTable1.getSelectedRow(), 4).toString();
        String per = tableModel.getValueAt(jTable1.getSelectedRow(), 5).toString();
        String saleTime = tableModel.getValueAt(jTable1.getSelectedRow(), 6).toString();
        //to set Data into the fields
        id.setText(ID);
        name.setText(proName);
        type.setSelectedItem(proType);
        quan.setSelectedItem(quantity);
        price.setText(proPrice);
        SalePer.setSelectedItem(per);
        time.setText(saleTime);
        for (int i = 0; i < M.getSalesList().size(); i++) {
            Sales s = (Sales) (M.getSalesList().get(i));
            if (ID.equals(s.getProductID())) {
                s.setProductID("");
                s.setNewPrice(0);
                s.setSalesPercentage("");
                s.setSalesTimeDuration("");
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void quanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewProductsIntoSale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewProductsIntoSale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewProductsIntoSale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewProductsIntoSale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewProductsIntoSale().setVisible(true);
            }
        });
    }
    ManagingSystem M = ManagingSystem.getInstance();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JLabel CloseLabel;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JLabel MinLabel;
    private javax.swing.JPanel MinPannel;
    private javax.swing.JComboBox<String> SalePer;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JPanel closePannel;
    private javax.swing.JTextArea desc;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField price;
    private javax.swing.JComboBox<String> quan;
    private javax.swing.JTextField time;
    private javax.swing.JComboBox<String> type;
    // End of variables declaration//GEN-END:variables
}
