/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject;

/**
 *
 * @author Hafsa Rashid
 */
public class Appliances extends javax.swing.JFrame {

    /**
     * Creates new form Appliances
     */
    public Appliances() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        med2 = new javax.swing.JLabel();
        button2 = new javax.swing.JButton();
        label2 = new javax.swing.JLabel();
        prd2 = new javax.swing.JLabel();
        prd3 = new javax.swing.JLabel();
        med3 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        button3 = new javax.swing.JButton();
        prd4 = new javax.swing.JLabel();
        med4 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        button4 = new javax.swing.JButton();
        prd5 = new javax.swing.JLabel();
        med5 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        button5 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        prd6 = new javax.swing.JLabel();
        med6 = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();
        button6 = new javax.swing.JButton();
        med7 = new javax.swing.JLabel();
        button7 = new javax.swing.JButton();
        prd7 = new javax.swing.JLabel();
        label7 = new javax.swing.JLabel();
        med8 = new javax.swing.JLabel();
        button8 = new javax.swing.JButton();
        prd8 = new javax.swing.JLabel();
        label8 = new javax.swing.JLabel();
        prd9 = new javax.swing.JLabel();
        med9 = new javax.swing.JLabel();
        label9 = new javax.swing.JLabel();
        button9 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setMinimumSize(new java.awt.Dimension(1140, 710));
        jPanel1.setPreferredSize(new java.awt.Dimension(1063, 691));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(190, 21, 88));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Appliances");
        jPanel2.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, -1));

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/icons8_minimize_window_30px.png"))); // NOI18N
        jPanel2.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, 29, 33));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/icons8_multiply_30px_1.png"))); // NOI18N
        jPanel2.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 10, -1, 33));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 50));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/app4.jpg"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 83, -1, -1));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/app5.jpg"))); // NOI18N
        jLabel2.setToolTipText("");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 83, -1, -1));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/app8.jpg"))); // NOI18N
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 83, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/app7.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 90, 290, 230));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 56, -1, 257));

        med2.setText("Door mat");
        jPanel1.add(med2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 330, 90, 20));

        button2.setBackground(new java.awt.Color(204, 204, 255));
        button2.setText("Add to cart");
        jPanel1.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 350, 120, 20));

        label2.setText("PKR 800/-");
        jPanel1.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 350, 90, 20));

        prd2.setText("Product-04");
        jPanel1.add(prd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 330, 90, 20));

        prd3.setText("Product-03");
        jPanel1.add(prd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 90, 20));

        med3.setText("Bedroom Rug");
        jPanel1.add(med3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, 80, 20));

        label3.setText("PKR 1800/-");
        jPanel1.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, 90, 20));

        button3.setBackground(new java.awt.Color(204, 204, 255));
        button3.setText("Add to cart");
        jPanel1.add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, 100, 20));

        prd4.setText("Product-02");
        jPanel1.add(prd4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 90, 20));

        med4.setText("Tea pot");
        jPanel1.add(med4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 90, 20));

        label4.setText("PKR 2800/-");
        jPanel1.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 90, 20));

        button4.setBackground(new java.awt.Color(204, 204, 255));
        button4.setText("Add to cart");
        jPanel1.add(button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 100, 20));

        prd5.setText("Product-01");
        jPanel1.add(prd5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 90, 20));

        med5.setText("Spoon set");
        jPanel1.add(med5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 60, 20));

        label5.setText("PKR 2200/-");
        jPanel1.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 90, 20));

        button5.setBackground(new java.awt.Color(204, 204, 255));
        button5.setText("Add to cart");
        jPanel1.add(button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 100, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/app6.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 150, 230));

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/app9.jpg"))); // NOI18N
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 0, 150, 230));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 150, 230));

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/app1.jpg"))); // NOI18N
        jPanel9.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 230));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 240, 230));

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/app2.jpg"))); // NOI18N
        jLabel9.setToolTipText("");
        jPanel10.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 230));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 380, 260, 230));

        prd6.setText("Product-05");
        jPanel1.add(prd6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, 90, 20));

        med6.setText("Decoration");
        jPanel1.add(med6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 620, 70, 20));

        label6.setText("PKR 2000/-");
        jPanel1.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, 90, 20));

        button6.setBackground(new java.awt.Color(204, 204, 255));
        button6.setText("Add to cart");
        jPanel1.add(button6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 640, 100, 20));

        med7.setText("Lamp");
        jPanel1.add(med7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 620, 90, 20));

        button7.setBackground(new java.awt.Color(204, 204, 255));
        button7.setText("Add to cart");
        jPanel1.add(button7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 640, 100, 20));

        prd7.setText("Product-06");
        jPanel1.add(prd7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 620, 90, 20));

        label7.setText("PKR 2500/-");
        jPanel1.add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 640, 90, 20));

        med8.setText("Side clock");
        jPanel1.add(med8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 620, 90, 20));

        button8.setBackground(new java.awt.Color(204, 204, 255));
        button8.setText("Add to cart");
        jPanel1.add(button8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 640, 110, 20));

        prd8.setText("Product-07");
        jPanel1.add(prd8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 620, 90, 20));

        label8.setText("PKR 2400/-");
        jPanel1.add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 640, 90, 20));

        prd9.setText("Product-08");
        jPanel1.add(prd9, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 620, 90, 20));

        med9.setText("Dinner set");
        jPanel1.add(med9, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 620, 100, 20));

        label9.setText("PKR 3000/-");
        jPanel1.add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 640, 90, 20));

        button9.setBackground(new java.awt.Color(204, 204, 255));
        button9.setText("Add to cart");
        jPanel1.add(button9, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 640, 100, 20));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/wallpaper6.jpg"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1060, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Appliances.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Appliances.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Appliances.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Appliances.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Appliances().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    private javax.swing.JButton button5;
    private javax.swing.JButton button6;
    private javax.swing.JButton button7;
    private javax.swing.JButton button8;
    private javax.swing.JButton button9;
    private javax.swing.JLabel close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel label9;
    private javax.swing.JLabel med2;
    private javax.swing.JLabel med3;
    private javax.swing.JLabel med4;
    private javax.swing.JLabel med5;
    private javax.swing.JLabel med6;
    private javax.swing.JLabel med7;
    private javax.swing.JLabel med8;
    private javax.swing.JLabel med9;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel prd2;
    private javax.swing.JLabel prd3;
    private javax.swing.JLabel prd4;
    private javax.swing.JLabel prd5;
    private javax.swing.JLabel prd6;
    private javax.swing.JLabel prd7;
    private javax.swing.JLabel prd8;
    private javax.swing.JLabel prd9;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
