/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject;

/**
 *
 * @author Hafsa Rashid
 */
public class Clothes extends javax.swing.JFrame {

    /**
     * Creates new form Clothes
     */
    public Clothes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        pic1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        pic2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        pic3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        button8 = new javax.swing.JButton();
        dress2 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        button2 = new javax.swing.JButton();
        label3 = new javax.swing.JLabel();
        button4 = new javax.swing.JButton();
        label4 = new javax.swing.JLabel();
        pic4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        pic5 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        button5 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        pic6 = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();
        button6 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        pic7 = new javax.swing.JLabel();
        label7 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        pic8 = new javax.swing.JLabel();
        label8 = new javax.swing.JLabel();
        button3 = new javax.swing.JButton();
        button1 = new javax.swing.JButton();
        button7 = new javax.swing.JButton();
        prd1 = new javax.swing.JLabel();
        label10 = new javax.swing.JLabel();
        prd2 = new javax.swing.JLabel();
        dress1 = new javax.swing.JLabel();
        prd3 = new javax.swing.JLabel();
        dress3 = new javax.swing.JLabel();
        prd7 = new javax.swing.JLabel();
        dress7 = new javax.swing.JLabel();
        prd6 = new javax.swing.JLabel();
        dress6 = new javax.swing.JLabel();
        prd5 = new javax.swing.JLabel();
        dress5 = new javax.swing.JLabel();
        prd4 = new javax.swing.JLabel();
        dress4 = new javax.swing.JLabel();
        prd8 = new javax.swing.JLabel();
        dress8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(190, 21, 88));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Dresses");
        jPanel2.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 180, -1));

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/icons8_minimize_window_30px.png"))); // NOI18N
        jPanel2.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, 29, 33));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/icons8_multiply_30px_1.png"))); // NOI18N
        jPanel2.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, -1, 33));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 50));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pic1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/shirt1.jpeg"))); // NOI18N
        pic1.setToolTipText("");
        jPanel3.add(pic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 150, 200));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pic2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/shirt2.jpeg"))); // NOI18N
        pic2.setToolTipText("");
        jPanel4.add(pic2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 200));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 180, 190));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pic3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/scarf1.jpeg"))); // NOI18N
        pic3.setToolTipText("");
        jPanel5.add(pic3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 190, 200));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, 120, -1));

        button8.setBackground(new java.awt.Color(204, 204, 255));
        button8.setText("Add to cart");
        jPanel1.add(button8, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 600, 100, 20));

        dress2.setText("Pink Shirt and jeans");
        jPanel1.add(dress2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 110, 20));

        label2.setText("PKR 2000/-");
        jPanel1.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 80, 20));

        button2.setBackground(new java.awt.Color(204, 204, 255));
        button2.setText("Add to cart");
        jPanel1.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 110, 20));

        label3.setText("PKR 900/-");
        jPanel1.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 100, 20));

        button4.setBackground(new java.awt.Color(204, 204, 255));
        button4.setText("Add to cart");
        jPanel1.add(button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 320, -1, 20));

        label4.setText("PKR 1500/-");
        jPanel1.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 320, 90, 20));

        pic4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/pant3.jpeg"))); // NOI18N
        pic4.setToolTipText("");
        jPanel1.add(pic4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, 140, 190));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pic5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/shirt5.jpeg"))); // NOI18N
        pic5.setToolTipText("");
        jPanel7.add(pic5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 210));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 160, 210));

        label5.setText("PKR 3500/-");
        jPanel1.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 70, 20));

        button5.setBackground(new java.awt.Color(204, 204, 255));
        button5.setText("Add to cart");
        jPanel1.add(button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 600, 110, 20));

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pic6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/sweater2.jpeg"))); // NOI18N
        pic6.setToolTipText("");
        jPanel8.add(pic6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 210));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, -1, 210));

        label6.setText("PKR 3000/-");
        jPanel1.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 600, 80, 20));

        button6.setBackground(new java.awt.Color(204, 204, 255));
        button6.setText("Add to cart");
        jPanel1.add(button6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 600, 110, 20));

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pic7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/bottom1.jpeg"))); // NOI18N
        pic7.setToolTipText("");
        jPanel9.add(pic7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 210));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, -1, 210));

        label7.setText("PKR 1800/-");
        jPanel1.add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 600, 70, 20));

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pic8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/sweater.jpeg"))); // NOI18N
        pic8.setToolTipText("");
        jPanel10.add(pic8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 210));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 360, 160, 220));

        label8.setText("PKR 2500/-");
        jPanel1.add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 600, 70, 20));

        button3.setBackground(new java.awt.Color(204, 204, 255));
        button3.setText("Add to cart");
        jPanel1.add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 110, 20));

        button1.setBackground(new java.awt.Color(204, 204, 255));
        button1.setText("Add to cart");
        jPanel1.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 100, 20));

        button7.setBackground(new java.awt.Color(204, 204, 255));
        button7.setText("Add to cart");
        jPanel1.add(button7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 600, 100, 20));

        prd1.setText("Product-01");
        jPanel1.add(prd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 90, 20));

        label10.setText("PKR 1200/-");
        jPanel1.add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 90, 20));

        prd2.setText("Product-02");
        jPanel1.add(prd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 80, 20));

        dress1.setText("White Shirt");
        jPanel1.add(dress1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 80, 20));

        prd3.setText("Product-03");
        jPanel1.add(prd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 80, 20));

        dress3.setText("Gray Scarf");
        jPanel1.add(dress3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 90, 20));

        prd7.setText("Product-04");
        jPanel1.add(prd7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 580, 80, 20));

        dress7.setText("Gray Bottom");
        jPanel1.add(dress7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 580, 80, 20));

        prd6.setText("Product-04");
        jPanel1.add(prd6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 580, 80, 20));

        dress6.setText("Blue Sweater");
        jPanel1.add(dress6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 580, 80, 20));

        prd5.setText("Product-04");
        jPanel1.add(prd5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 80, 20));

        dress5.setText("Black Jacket");
        jPanel1.add(dress5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 580, 80, 20));

        prd4.setText("Product-04");
        jPanel1.add(prd4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 290, 80, 20));

        dress4.setText("White bottom");
        jPanel1.add(dress4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 290, 80, 20));

        prd8.setText("Product-05");
        jPanel1.add(prd8, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 580, 80, 20));

        dress8.setText("Pink Sweater");
        jPanel1.add(dress8, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 580, 80, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clothes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clothes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clothes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clothes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clothes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    private javax.swing.JButton button5;
    private javax.swing.JButton button6;
    private javax.swing.JButton button7;
    private javax.swing.JButton button8;
    private javax.swing.JLabel close;
    private javax.swing.JLabel dress1;
    private javax.swing.JLabel dress2;
    private javax.swing.JLabel dress3;
    private javax.swing.JLabel dress4;
    private javax.swing.JLabel dress5;
    private javax.swing.JLabel dress6;
    private javax.swing.JLabel dress7;
    private javax.swing.JLabel dress8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel label10;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel pic1;
    private javax.swing.JLabel pic2;
    private javax.swing.JLabel pic3;
    private javax.swing.JLabel pic4;
    private javax.swing.JLabel pic5;
    private javax.swing.JLabel pic6;
    private javax.swing.JLabel pic7;
    private javax.swing.JLabel pic8;
    private javax.swing.JLabel prd1;
    private javax.swing.JLabel prd2;
    private javax.swing.JLabel prd3;
    private javax.swing.JLabel prd4;
    private javax.swing.JLabel prd5;
    private javax.swing.JLabel prd6;
    private javax.swing.JLabel prd7;
    private javax.swing.JLabel prd8;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
