/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author KHADIJA
 */
public class CustomerMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public CustomerMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        closePannel = new javax.swing.JPanel();
        CloseLabel = new javax.swing.JLabel();
        MinPannel = new javax.swing.JPanel();
        MinLabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        GuestButton = new javax.swing.JButton();
        SignUpButton = new javax.swing.JButton();
        SigninButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(190, 21, 88));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(190, 21, 88));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closePannel.setBackground(new java.awt.Color(190, 21, 88));

        CloseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CloseLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/icons8_multiply_40px.png"))); // NOI18N
        CloseLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CloseLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CloseLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout closePannelLayout = new javax.swing.GroupLayout(closePannel);
        closePannel.setLayout(closePannelLayout);
        closePannelLayout.setHorizontalGroup(
            closePannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, closePannelLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(CloseLabel)
                .addContainerGap())
        );
        closePannelLayout.setVerticalGroup(
            closePannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(closePannelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CloseLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(closePannel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 80, 60));

        MinPannel.setBackground(new java.awt.Color(190, 21, 88));

        MinLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MinLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/icons8_minimize_window_40px_1.png"))); // NOI18N
        MinLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MinLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MinLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout MinPannelLayout = new javax.swing.GroupLayout(MinPannel);
        MinPannel.setLayout(MinPannelLayout);
        MinPannelLayout.setHorizontalGroup(
            MinPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MinPannelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(MinLabel)
                .addContainerGap())
        );
        MinPannelLayout.setVerticalGroup(
            MinPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MinPannelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MinLabel)
                .addContainerGap())
        );

        jPanel3.add(MinPannel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 60));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 200, 60));

        jPanel6.setBackground(new java.awt.Color(190, 21, 88));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("One-Click Pick");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 319, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 60));

        GuestButton.setBackground(new java.awt.Color(190, 21, 88));
        GuestButton.setForeground(new java.awt.Color(255, 255, 255));
        GuestButton.setText("Login as Guest");
        GuestButton.setBorderPainted(false);
        GuestButton.setDefaultCapable(false);
        GuestButton.setFocusPainted(false);
        GuestButton.setFocusable(false);
        GuestButton.setRequestFocusEnabled(false);
        GuestButton.setRolloverEnabled(false);
        GuestButton.setVerifyInputWhenFocusTarget(false);
        GuestButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GuestButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GuestButtonMouseExited(evt);
            }
        });
        GuestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuestButtonActionPerformed(evt);
            }
        });
        jPanel1.add(GuestButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 460, 230, 40));

        SignUpButton.setBackground(new java.awt.Color(190, 21, 88));
        SignUpButton.setForeground(new java.awt.Color(255, 255, 255));
        SignUpButton.setText("Sign Up");
        SignUpButton.setBorderPainted(false);
        SignUpButton.setDefaultCapable(false);
        SignUpButton.setFocusPainted(false);
        SignUpButton.setFocusable(false);
        SignUpButton.setRequestFocusEnabled(false);
        SignUpButton.setRolloverEnabled(false);
        SignUpButton.setVerifyInputWhenFocusTarget(false);
        SignUpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SignUpButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignUpButtonMouseExited(evt);
            }
        });
        SignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SignUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 400, 230, 40));

        SigninButton.setBackground(new java.awt.Color(190, 21, 88));
        SigninButton.setForeground(new java.awt.Color(255, 255, 255));
        SigninButton.setText("Sign in");
        SigninButton.setBorderPainted(false);
        SigninButton.setDefaultCapable(false);
        SigninButton.setFocusPainted(false);
        SigninButton.setFocusable(false);
        SigninButton.setRequestFocusEnabled(false);
        SigninButton.setRolloverEnabled(false);
        SigninButton.setVerifyInputWhenFocusTarget(false);
        SigninButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SigninButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SigninButtonMouseExited(evt);
            }
        });
        SigninButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SigninButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SigninButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 340, 230, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/edit.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1000, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
     public void changeColor(JPanel hover, Color rand)
     {
         hover.setBackground(rand);
     }
     
    private void CloseLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_CloseLabelMouseClicked

    private void CloseLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMouseEntered
        // TODO add your handling code here:
        changeColor(closePannel, new Color(222, 142, 174));
    }//GEN-LAST:event_CloseLabelMouseEntered

    private void CloseLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMouseExited
        // TODO add your handling code here:
        changeColor(closePannel, new Color(190,21,88));
    }//GEN-LAST:event_CloseLabelMouseExited

    private void MinLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinLabelMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(MainScreen.ICONIFIED);
    }//GEN-LAST:event_MinLabelMouseClicked

    private void MinLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinLabelMouseEntered
        // TODO add your handling code here:
        changeColor(MinPannel, new Color(222, 142, 174));
    }//GEN-LAST:event_MinLabelMouseEntered

    private void MinLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinLabelMouseExited
        // TODO add your handling code here:
        changeColor(MinPannel, new Color(190,21,88));
    }//GEN-LAST:event_MinLabelMouseExited

    private void SignUpButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpButtonMouseEntered
        // TODO add your handling code here:
        SignUpButton.setBackground(new Color(222, 142, 174));
    }//GEN-LAST:event_SignUpButtonMouseEntered

    private void SignUpButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpButtonMouseExited
        // TODO add your handling code here:
        SignUpButton.setBackground(new Color(190,21,88));
    }//GEN-LAST:event_SignUpButtonMouseExited

    private void GuestButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuestButtonMouseEntered
        // TODO add your handling code here:
        GuestButton.setBackground(new Color(222, 142, 174));
    }//GEN-LAST:event_GuestButtonMouseEntered

    private void GuestButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuestButtonMouseExited
        // TODO add your handling code here:
        GuestButton.setBackground(new Color(190,21,88));
    }//GEN-LAST:event_GuestButtonMouseExited

    private void SigninButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SigninButtonActionPerformed
        // TODO add your handling code here:
        CustomerSignin signin = new CustomerSignin();
        signin.setVisible(true);
    }//GEN-LAST:event_SigninButtonActionPerformed

    private void SigninButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SigninButtonMouseEntered
        // TODO add your handling code here:
        SigninButton.setBackground(new Color(222, 142, 174));
    }//GEN-LAST:event_SigninButtonMouseEntered

    private void SigninButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SigninButtonMouseExited
        // TODO add your handling code here:
        SigninButton.setBackground(new Color(190,21,88));
    }//GEN-LAST:event_SigninButtonMouseExited

    private void GuestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuestButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuestButtonActionPerformed

    private void SignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButtonActionPerformed
        // TODO add your handling code here:
        CustomerSignup signup = new CustomerSignup();
        signup.setVisible(true);
    }//GEN-LAST:event_SignUpButtonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CloseLabel;
    private javax.swing.JButton GuestButton;
    private javax.swing.JLabel MinLabel;
    private javax.swing.JPanel MinPannel;
    private javax.swing.JButton SignUpButton;
    private javax.swing.JButton SigninButton;
    private javax.swing.JPanel closePannel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
