/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject;

/**
 *
 * @author Hafsa Rashid
 */
public class PharmacyForm extends javax.swing.JFrame {

    /**
     * Creates new form PharmacyForm
     */
    public PharmacyForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        prd1 = new javax.swing.JLabel();
        med1 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        button1 = new javax.swing.JButton();
        prd2 = new javax.swing.JLabel();
        med2 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        button2 = new javax.swing.JButton();
        prd3 = new javax.swing.JLabel();
        med3 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        button3 = new javax.swing.JButton();
        prd4 = new javax.swing.JLabel();
        med4 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        button4 = new javax.swing.JButton();
        button5 = new javax.swing.JButton();
        label5 = new javax.swing.JLabel();
        med8 = new javax.swing.JLabel();
        prd5 = new javax.swing.JLabel();
        button6 = new javax.swing.JButton();
        label6 = new javax.swing.JLabel();
        med7 = new javax.swing.JLabel();
        prd6 = new javax.swing.JLabel();
        prd7 = new javax.swing.JLabel();
        button7 = new javax.swing.JButton();
        med6 = new javax.swing.JLabel();
        label7 = new javax.swing.JLabel();
        prd8 = new javax.swing.JLabel();
        button8 = new javax.swing.JButton();
        med5 = new javax.swing.JLabel();
        label8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(1155, 764));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(190, 21, 88));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Pharmacy");
        jPanel2.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 140, -1));

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/icons8_minimize_window_30px.png"))); // NOI18N
        jPanel2.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 10, 29, 33));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/icons8_multiply_30px_1.png"))); // NOI18N
        jPanel2.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 10, -1, 33));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 50));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/med2.jpg"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 76, -1, -1));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/med4.jpg"))); // NOI18N
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 250));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 170, 250));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/med1.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 280, 220));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/med8.jpg"))); // NOI18N
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 240));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 230, 240));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/med5.jpg"))); // NOI18N
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 240));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 230, 240));

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/med6.jpg"))); // NOI18N
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 230));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 80, 190, 230));

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/med3.jpg"))); // NOI18N
        jPanel9.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 240));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, 250, 240));

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/med7.jpg"))); // NOI18N
        jPanel10.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 240));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 410, 170, 240));

        prd1.setText("Product-01");
        jPanel1.add(prd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 90, 20));

        med1.setText("First Aid");
        jPanel1.add(med1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 90, 20));

        label1.setText("PKR 600/-");
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 90, 20));

        button1.setBackground(new java.awt.Color(204, 204, 255));
        button1.setText("Add to cart");
        jPanel1.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 100, 20));

        prd2.setText("Product-02");
        jPanel1.add(prd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 90, 20));

        med2.setText("Med Kit");
        jPanel1.add(med2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 90, 20));

        label2.setText("PKR 800/-");
        jPanel1.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 90, 20));

        button2.setBackground(new java.awt.Color(204, 204, 255));
        button2.setText("Add to cart");
        jPanel1.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 100, 20));

        prd3.setText("Product-03");
        jPanel1.add(prd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 330, 90, 20));

        med3.setText("Thermometer");
        jPanel1.add(med3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 330, 110, 20));

        label3.setText("PKR 1600/-");
        jPanel1.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 350, 90, 20));

        button3.setBackground(new java.awt.Color(204, 204, 255));
        button3.setText("Add to cart");
        jPanel1.add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 350, 100, 20));

        prd4.setText("Product-04");
        jPanel1.add(prd4, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 320, 90, 20));

        med4.setText("Sanitizer");
        jPanel1.add(med4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 320, 60, 20));

        label4.setText("PKR 250/-");
        jPanel1.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 340, 90, 20));

        button4.setBackground(new java.awt.Color(204, 204, 255));
        button4.setText("Add to cart");
        jPanel1.add(button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 340, 100, 20));

        button5.setBackground(new java.awt.Color(204, 204, 255));
        button5.setText("Add to cart");
        jPanel1.add(button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 680, 100, 20));

        label5.setText("PKR 400/-");
        jPanel1.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 680, 90, 20));

        med8.setText("Multi-Vitamins");
        jPanel1.add(med8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 660, 90, 20));

        prd5.setText("Product-8");
        jPanel1.add(prd5, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 660, 90, 20));

        button6.setBackground(new java.awt.Color(204, 204, 255));
        button6.setText("Add to cart");
        jPanel1.add(button6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 680, 100, 20));

        label6.setText("PKR 300/-");
        jPanel1.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 680, 90, 20));

        med7.setText("Medicines");
        jPanel1.add(med7, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 660, 90, 20));

        prd6.setText("Product-07");
        jPanel1.add(prd6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 660, 90, 20));

        prd7.setText("Product-06");
        jPanel1.add(prd7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 660, 90, 20));

        button7.setBackground(new java.awt.Color(204, 204, 255));
        button7.setText("Add to cart");
        jPanel1.add(button7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 680, 100, 20));

        med6.setText("Tissues");
        jPanel1.add(med6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 660, 80, 20));

        label7.setText("PKR 200/-");
        jPanel1.add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 680, 90, 20));

        prd8.setText("Product-05");
        jPanel1.add(prd8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 660, 90, 20));

        button8.setBackground(new java.awt.Color(204, 204, 255));
        button8.setText("Add to cart");
        jPanel1.add(button8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 680, 100, 20));

        med5.setText("Pills case");
        jPanel1.add(med5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 660, 70, 20));

        label8.setText("PKR 500/-");
        jPanel1.add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 680, 90, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/wallpaper5.jpg"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 50, 1150, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1140, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PharmacyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PharmacyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PharmacyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PharmacyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PharmacyForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    private javax.swing.JButton button5;
    private javax.swing.JButton button6;
    private javax.swing.JButton button7;
    private javax.swing.JButton button8;
    private javax.swing.JLabel close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel med1;
    private javax.swing.JLabel med2;
    private javax.swing.JLabel med3;
    private javax.swing.JLabel med4;
    private javax.swing.JLabel med5;
    private javax.swing.JLabel med6;
    private javax.swing.JLabel med7;
    private javax.swing.JLabel med8;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel prd1;
    private javax.swing.JLabel prd2;
    private javax.swing.JLabel prd3;
    private javax.swing.JLabel prd4;
    private javax.swing.JLabel prd5;
    private javax.swing.JLabel prd6;
    private javax.swing.JLabel prd7;
    private javax.swing.JLabel prd8;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
