/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KHADIJA
 */
public class ProductsFrame extends javax.swing.JFrame {

    /**
     * Creates new form ProductsFrame
     */
    Customer_Director c = new Customer_Director();

    public ProductsFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        glossPainter1 = new org.jdesktop.swingx.painter.GlossPainter();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        closePannel = new javax.swing.JPanel();
        CloseLabel = new javax.swing.JLabel();
        MinPannel = new javax.swing.JPanel();
        MinLabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ProductID = new javax.swing.JTextField();
        ProductPrice = new javax.swing.JTextField();
        ProductName = new javax.swing.JTextField();
        ProductType = new javax.swing.JComboBox<>();
        QuantityCombo = new javax.swing.JComboBox<>();
        AddButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(190, 21, 88));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(190, 21, 88));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closePannel.setBackground(new java.awt.Color(190, 21, 88));

        CloseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CloseLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/icons8_multiply_40px.png"))); // NOI18N
        CloseLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CloseLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CloseLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout closePannelLayout = new javax.swing.GroupLayout(closePannel);
        closePannel.setLayout(closePannelLayout);
        closePannelLayout.setHorizontalGroup(
            closePannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CloseLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        closePannelLayout.setVerticalGroup(
            closePannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CloseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel3.add(closePannel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 70, 60));

        MinPannel.setBackground(new java.awt.Color(190, 21, 88));

        MinLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MinLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/icons8_minimize_window_40px_1.png"))); // NOI18N
        MinLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MinLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MinLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout MinPannelLayout = new javax.swing.GroupLayout(MinPannel);
        MinPannel.setLayout(MinPannelLayout);
        MinPannelLayout.setHorizontalGroup(
            MinPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MinLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        MinPannelLayout.setVerticalGroup(
            MinPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MinLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel3.add(MinPannel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 60, 60));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 210, 60));

        jPanel6.setBackground(new java.awt.Color(190, 21, 88));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("One-Click Pick");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 319, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 60));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(190, 21, 88));
        jLabel2.setText("      Handle Products");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 310, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(190, 21, 88));
        jLabel3.setText("Product ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(190, 21, 88));
        jLabel4.setText("Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(190, 21, 88));
        jLabel5.setText("Quantity");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(190, 21, 88));
        jLabel6.setText("Price");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(190, 21, 88));
        jLabel7.setText("Type");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, -1, -1));

        ProductID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(190, 21, 88)));
        ProductID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductIDActionPerformed(evt);
            }
        });
        jPanel1.add(ProductID, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 270, 30));

        ProductPrice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(190, 21, 88)));
        jPanel1.add(ProductPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, 270, 30));

        ProductName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(190, 21, 88)));
        jPanel1.add(ProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 270, 30));

        ProductType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grocery", "Dresses", "Books", "Stationary", "Pharmacy", "Home Appliances", "" }));
        ProductType.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(190, 21, 88)));
        jPanel1.add(ProductType, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, 270, 30));

        QuantityCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        QuantityCombo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(190, 21, 88)));
        QuantityCombo.setFocusable(false);
        QuantityCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantityComboActionPerformed(evt);
            }
        });
        jPanel1.add(QuantityCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 270, 30));

        AddButton.setBackground(new java.awt.Color(190, 21, 88));
        AddButton.setForeground(new java.awt.Color(255, 255, 255));
        AddButton.setText("Add Product");
        AddButton.setBorder(null);
        AddButton.setBorderPainted(false);
        AddButton.setDefaultCapable(false);
        AddButton.setFocusPainted(false);
        AddButton.setFocusable(false);
        AddButton.setRequestFocusEnabled(false);
        AddButton.setRolloverEnabled(false);
        AddButton.setVerifyInputWhenFocusTarget(false);
        AddButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddButtonMouseExited(evt);
            }
        });
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 140, 40));

        UpdateButton.setBackground(new java.awt.Color(190, 21, 88));
        UpdateButton.setForeground(new java.awt.Color(255, 255, 255));
        UpdateButton.setText("Update Product");
        UpdateButton.setBorder(null);
        UpdateButton.setBorderPainted(false);
        UpdateButton.setDefaultCapable(false);
        UpdateButton.setFocusPainted(false);
        UpdateButton.setFocusable(false);
        UpdateButton.setRequestFocusEnabled(false);
        UpdateButton.setRolloverEnabled(false);
        UpdateButton.setVerifyInputWhenFocusTarget(false);
        UpdateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UpdateButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UpdateButtonMouseExited(evt);
            }
        });
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });
        jPanel1.add(UpdateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 510, 140, 40));

        DeleteButton.setBackground(new java.awt.Color(190, 21, 88));
        DeleteButton.setForeground(new java.awt.Color(255, 255, 255));
        DeleteButton.setText("Delete Product");
        DeleteButton.setBorder(null);
        DeleteButton.setBorderPainted(false);
        DeleteButton.setDefaultCapable(false);
        DeleteButton.setFocusPainted(false);
        DeleteButton.setFocusable(false);
        DeleteButton.setRequestFocusEnabled(false);
        DeleteButton.setRolloverEnabled(false);
        DeleteButton.setVerifyInputWhenFocusTarget(false);
        DeleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DeleteButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DeleteButtonMouseExited(evt);
            }
        });
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });
        jPanel1.add(DeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 510, 150, 40));

        jTable1.setForeground(new java.awt.Color(190, 21, 88));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Name", "Quantity", "Price", "Type"
            }
        ));
        jTable1.setSelectionBackground(new java.awt.Color(190, 21, 88));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 580, 770, 90));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/2.jpg"))); // NOI18N
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(190, 21, 88)));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 920, 680));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
  public void changeColor(JPanel hover, Color rand) {
        hover.setBackground(rand);
    }
    private void CloseLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_CloseLabelMouseClicked

    private void CloseLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMouseEntered
        // TODO add your handling code here:
        changeColor(closePannel, new Color(222, 142, 174));
    }//GEN-LAST:event_CloseLabelMouseEntered

    private void CloseLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMouseExited
        // TODO add your handling code here:
        changeColor(closePannel, new Color(190, 21, 88));
    }//GEN-LAST:event_CloseLabelMouseExited

    private void MinLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinLabelMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(MainScreen.ICONIFIED);
    }//GEN-LAST:event_MinLabelMouseClicked

    private void MinLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinLabelMouseEntered
        // TODO add your handling code here:
        changeColor(MinPannel, new Color(222, 142, 174));
    }//GEN-LAST:event_MinLabelMouseEntered

    private void MinLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinLabelMouseExited
        // TODO add your handling code here:
        changeColor(MinPannel, new Color(190, 21, 88));
    }//GEN-LAST:event_MinLabelMouseExited

    private void ProductIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductIDActionPerformed

    private void AddButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButtonMouseEntered
        // TODO add your handling code here:
        AddButton.setBackground(new Color(222, 142, 174));
    }//GEN-LAST:event_AddButtonMouseEntered

    private void AddButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButtonMouseExited
        // TODO add your handling code here:
        AddButton.setBackground(new Color(190, 21, 88));
    }//GEN-LAST:event_AddButtonMouseExited

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:

        Products pro = new Products();
        Validator check = new Validator();
        pro.setProductID(ProductID.getText());
        pro.setProductName(ProductName.getText());
        int price = Integer.parseInt(ProductPrice.getText());
        pro.setProductPrice(price);
        int quantity = Integer.parseInt(QuantityCombo.getSelectedItem().toString());
        pro.setProductQuantity(quantity);
        pro.setProductType(ProductType.getSelectedItem().toString());
        boolean checkProductID = check.ProductID(pro.getProductID());
        boolean checkProductName = check.ProductName(pro.getProductName());
        boolean checkProductPrice = check.ProductPrice(pro.getProductPrice());
        if (ProductID.getText().equals("") || ProductName.getText().equals("") || ProductPrice.getText().equals("") || QuantityCombo.getSelectedItem().toString().equals("") || ProductType.getSelectedItem().toString().equals("")) {

            JOptionPane.showMessageDialog(null, "You have not entered all required Data");
        } else {
            if (checkProductID == true && checkProductName == true && checkProductPrice == true) {
                String data[] = {ProductID.getText(), ProductName.getText(), QuantityCombo.getSelectedItem().toString(), ProductPrice.getText(), ProductType.getSelectedItem().toString()};
                System.out.println(data.length);
                DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
                tableModel.addRow(data);
                M.add(pro, c);
                JOptionPane.showMessageDialog(null, "Your Data saved Successfully");
                for (int i = 0; i < Customer_Director.prod.size(); i++) {
                    System.out.println(c.prod.get(i));
                }
                ProductID.setText("");
                ProductName.setText("");
                ProductPrice.setText("");
            } else {
                System.out.println("Products Invalid");
            }
        }

    }//GEN-LAST:event_AddButtonActionPerformed

    private void UpdateButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateButtonMouseEntered
        // TODO add your handling code here:
        UpdateButton.setBackground(new Color(222, 142, 174));
    }//GEN-LAST:event_UpdateButtonMouseEntered

    private void UpdateButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateButtonMouseExited
        // TODO add your handling code here:
        UpdateButton.setBackground(new Color(190, 21, 88));
    }//GEN-LAST:event_UpdateButtonMouseExited

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
        if (jTable1.getSelectedRowCount() == 1) {
            Products pro = new Products();
            Validator check = new Validator();
            pro.setProductID(ProductID.getText());
            pro.setProductName(ProductName.getText());
            int price = 0;
            int quantity = 0;
            try {
                price = Integer.parseInt(ProductPrice.getText());
                pro.setProductPrice(price);
                quantity = Integer.parseInt(QuantityCombo.getSelectedItem().toString());
                pro.setProductQuantity(quantity);
            } catch (Exception e) {
                e.printStackTrace();
            }
            pro.setProductType(ProductType.getSelectedItem().toString());
            boolean checkProductID = check.ProductID(pro.getProductID());
            boolean checkProductName = check.ProductName(pro.getProductName());
            boolean checkProductPrice = check.ProductPrice(pro.getProductPrice());
            if (checkProductID == true && checkProductName == true && checkProductPrice == true) {
                String ID = ProductID.getText();
                String name = ProductName.getText();
                String Productprice = ProductPrice.getText();
                String Productquantity = QuantityCombo.getSelectedItem().toString();
                String type = ProductType.getSelectedItem().toString();
                tableModel.setValueAt(ID, jTable1.getSelectedRow(), 0);
                tableModel.setValueAt(name, jTable1.getSelectedRow(), 1);
                tableModel.setValueAt(Productquantity, jTable1.getSelectedRow(), 2);
                tableModel.setValueAt(Productprice, jTable1.getSelectedRow(), 3);
                tableModel.setValueAt(type, jTable1.getSelectedRow(), 4);
                for (int i = 0; i < Customer_Director.prod.size(); i++) {
                    Products p = Customer_Director.prod.get(i);
                    if (p.getProductID().equals("")) {
                        pro.setProductID(ID);
                        pro.setProductName(name);
                        pro.setProductPrice(price);
                        pro.setProductQuantity(quantity);
                        pro.setProductType(type);
                        Customer_Director.prod.set(i, pro);
                    }
                }
                for (int j = 0; j < Customer_Director.prod.size(); j++) {
                    System.out.println(Customer_Director.prod.get(j));
                }
                JOptionPane.showMessageDialog(null, "Data has been updated successfully");
                ProductID.setText("");
                ProductName.setText("");
                ProductPrice.setText("");

            }
        } else {
            if (jTable1.getSelectedRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "You have not selected any Row or may be selected Multiple Rows");
            } else {
                JOptionPane.showMessageDialog(null, "Update Failed");

            }
        }
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void DeleteButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteButtonMouseEntered
        // TODO add your handling code here:
        DeleteButton.setBackground(new Color(222, 142, 174));
    }//GEN-LAST:event_DeleteButtonMouseEntered

    private void DeleteButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteButtonMouseExited
        // TODO add your handling code here:
        DeleteButton.setBackground(new Color(190, 21, 88));
    }//GEN-LAST:event_DeleteButtonMouseExited

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
        if (jTable1.getSelectedRowCount() == 1) {

            String ID = tableModel.getValueAt(jTable1.getSelectedRow(), 0).toString();
            String name = tableModel.getValueAt(jTable1.getSelectedRow(), 1).toString();
            String price = tableModel.getValueAt(jTable1.getSelectedRow(), 2).toString();
            String quantity = tableModel.getValueAt(jTable1.getSelectedRow(), 3).toString();
            String type = tableModel.getValueAt(jTable1.getSelectedRow(), 4).toString();
            for (int i = 0; i < Customer_Director.prod.size(); i++) {
                Products pro = Customer_Director.prod.get(i);
                if (ID.equals(pro.getProductID()) && type.equals(pro.getProductType())) {
                    Customer_Director.prod.remove(i);
                }
            }
            tableModel.removeRow(jTable1.getSelectedRow());
            ProductID.setText("");
            ProductName.setText("");
            ProductPrice.setText("");
            JOptionPane.showMessageDialog(null, "Data has been Deleted successfully");
        } else {
            if (jTable1.getSelectedRow() == 0) {
                JOptionPane.showMessageDialog(null, "You have not selected any Row or may be selected Multiple Rows");
            } else {
                JOptionPane.showMessageDialog(null, "Delete action Failed");

            }
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void QuantityComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantityComboActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_QuantityComboActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
        String ID = tableModel.getValueAt(jTable1.getSelectedRow(), 0).toString();
        String name = tableModel.getValueAt(jTable1.getSelectedRow(), 1).toString();
        String price = tableModel.getValueAt(jTable1.getSelectedRow(), 2).toString();
        String quantity = tableModel.getValueAt(jTable1.getSelectedRow(), 3).toString();
        String type = tableModel.getValueAt(jTable1.getSelectedRow(), 4).toString();

        //to set Data into the fields
        ProductID.setText(ID);
        ProductName.setText(name);
        ProductPrice.setText(price);
        QuantityCombo.setSelectedItem(quantity);
        ProductType.setSelectedItem(type);
        for (int i = 0; i < Customer_Director.prod.size(); i++) {
            Products pro = Customer_Director.prod.get(i);
            if (ID.equals(pro.getProductID()) && type.equals(pro.getProductType())) {
                pro.setProductID("");
                pro.setProductName("");
                pro.setProductPrice(0);
                pro.setProductQuantity(0);
                pro.setProductType("");

            }
        }

    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductsFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductsFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductsFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductsFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductsFrame().setVisible(true);
            }
        });
    }
    ManagingSystem M = ManagingSystem.getInstance();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JLabel CloseLabel;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JLabel MinLabel;
    private javax.swing.JPanel MinPannel;
    private javax.swing.JTextField ProductID;
    private javax.swing.JTextField ProductName;
    private javax.swing.JTextField ProductPrice;
    private javax.swing.JComboBox<String> ProductType;
    private javax.swing.JComboBox<String> QuantityCombo;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JPanel closePannel;
    private org.jdesktop.swingx.painter.GlossPainter glossPainter1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
