/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject;

/**
 *
 * @author Hafsa Rashid
 */
public class StationaryForm extends javax.swing.JFrame {

    /**
     * Creates new form StationaryForm
     */
    public StationaryForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        prd1 = new javax.swing.JLabel();
        book1 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        button1 = new javax.swing.JButton();
        prd2 = new javax.swing.JLabel();
        book2 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        button2 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        prd3 = new javax.swing.JLabel();
        book3 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        button3 = new javax.swing.JButton();
        prd4 = new javax.swing.JLabel();
        book4 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        button4 = new javax.swing.JButton();
        label5 = new javax.swing.JLabel();
        book5 = new javax.swing.JLabel();
        button5 = new javax.swing.JButton();
        prd5 = new javax.swing.JLabel();
        prd6 = new javax.swing.JLabel();
        book6 = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();
        button6 = new javax.swing.JButton();
        prd7 = new javax.swing.JLabel();
        book7 = new javax.swing.JLabel();
        label7 = new javax.swing.JLabel();
        button7 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        prd8 = new javax.swing.JLabel();
        book8 = new javax.swing.JLabel();
        label8 = new javax.swing.JLabel();
        button8 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        prd9 = new javax.swing.JLabel();
        book9 = new javax.swing.JLabel();
        label9 = new javax.swing.JLabel();
        button9 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(1240, 694));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(190, 21, 88));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Stationary");
        jPanel2.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 160, -1));

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/icons8_minimize_window_30px.png"))); // NOI18N
        jPanel2.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 10, 29, 33));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/icons8_multiply_30px_1.png"))); // NOI18N
        jPanel2.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, -1, 33));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/stat5.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 170, 230));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/stat7.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 170, 230));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/stat2.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 209, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 150, 220));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/stat8.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 209, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 80, 200, 220));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/stat6.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, 230));

        prd1.setText("Product-01");
        jPanel1.add(prd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 90, 20));

        book1.setText("Black Notebooks");
        jPanel1.add(book1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 110, 20));

        label1.setText("PKR 1200/-");
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 90, 20));

        button1.setBackground(new java.awt.Color(204, 204, 255));
        button1.setText("Add to cart");
        jPanel1.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 100, 20));

        prd2.setText("Product-02");
        jPanel1.add(prd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 90, 20));

        book2.setText("White Pencils");
        jPanel1.add(book2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 90, 20));

        label2.setText("PKR 650/-");
        jPanel1.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 90, 20));

        button2.setBackground(new java.awt.Color(204, 204, 255));
        button2.setText("Add to cart");
        jPanel1.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 100, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/stat1.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 200, 230));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/stat3.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 230, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 390, 240, 230));

        prd3.setText("Product-03");
        jPanel1.add(prd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 90, 20));

        book3.setText("USB");
        jPanel1.add(book3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, 60, 20));

        label3.setText("PKR 1200/-");
        jPanel1.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 90, 20));

        button3.setBackground(new java.awt.Color(204, 204, 255));
        button3.setText("Add to cart");
        jPanel1.add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 100, 20));

        prd4.setText("Product-09");
        jPanel1.add(prd4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 630, 90, 20));

        book4.setText("Calculator");
        jPanel1.add(book4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 630, 60, 20));

        label4.setText("PKR 800/-");
        jPanel1.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 650, 90, 20));

        button4.setBackground(new java.awt.Color(204, 204, 255));
        button4.setText("Add to cart");
        jPanel1.add(button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 650, 100, 20));

        label5.setText("PKR 1450/-");
        jPanel1.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 650, 90, 20));

        book5.setText("Notebooks");
        jPanel1.add(book5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 630, 90, 20));

        button5.setBackground(new java.awt.Color(204, 204, 255));
        button5.setText("Add to cart");
        jPanel1.add(button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 650, 100, 20));

        prd5.setText("Product-06");
        jPanel1.add(prd5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 630, 90, 20));

        prd6.setText("Product-07");
        jPanel1.add(prd6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 630, 90, 20));

        book6.setText("Black Sharpener");
        jPanel1.add(book6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 630, 120, 20));

        label6.setText("PKR 550/-");
        jPanel1.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 650, 90, 20));

        button6.setBackground(new java.awt.Color(204, 204, 255));
        button6.setText("Add to cart");
        jPanel1.add(button6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 650, 100, 20));

        prd7.setText("Product-08");
        jPanel1.add(prd7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 630, 90, 20));

        book7.setText("Pencil Colors");
        jPanel1.add(book7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 630, 90, 20));

        label7.setText("PKR 1000/-");
        jPanel1.add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 650, 90, 20));

        button7.setBackground(new java.awt.Color(204, 204, 255));
        button7.setText("Add to cart");
        jPanel1.add(button7, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 650, 100, 20));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/stat4.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 230, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 390, 250, 230));

        prd8.setText("Product-04");
        jPanel1.add(prd8, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 320, 90, 20));

        book8.setText("Stapler");
        jPanel1.add(book8, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 320, 60, 20));

        label8.setText("PKR 800/-");
        jPanel1.add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 340, 90, 20));

        button8.setBackground(new java.awt.Color(204, 204, 255));
        button8.setText("Add to cart");
        jPanel1.add(button8, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 340, 100, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/stat9.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 80, 230, 230));

        prd9.setText("Product-05");
        jPanel1.add(prd9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 320, 90, 20));

        book9.setText("Scissor");
        jPanel1.add(book9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 320, 60, 20));

        label9.setText("PKR 450/-");
        jPanel1.add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 340, 90, 20));

        button9.setBackground(new java.awt.Color(204, 204, 255));
        button9.setText("Add to cart");
        jPanel1.add(button9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 340, 100, 20));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/Images/wallpaper2.jpg"))); // NOI18N
        jLabel10.setToolTipText("");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 44, 1240, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StationaryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StationaryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StationaryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StationaryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StationaryForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel book1;
    private javax.swing.JLabel book2;
    private javax.swing.JLabel book3;
    private javax.swing.JLabel book4;
    private javax.swing.JLabel book5;
    private javax.swing.JLabel book6;
    private javax.swing.JLabel book7;
    private javax.swing.JLabel book8;
    private javax.swing.JLabel book9;
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    private javax.swing.JButton button5;
    private javax.swing.JButton button6;
    private javax.swing.JButton button7;
    private javax.swing.JButton button8;
    private javax.swing.JButton button9;
    private javax.swing.JLabel close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel label9;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel prd1;
    private javax.swing.JLabel prd2;
    private javax.swing.JLabel prd3;
    private javax.swing.JLabel prd4;
    private javax.swing.JLabel prd5;
    private javax.swing.JLabel prd6;
    private javax.swing.JLabel prd7;
    private javax.swing.JLabel prd8;
    private javax.swing.JLabel prd9;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
